services:
  postgres-database:
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres-database
    ports:
      - ${POSTGRES_HOST_CONTAINER}
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - alma-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-cache:
    image: redis:latest
    restart: 'no'
    ports:
      - ${REDIS_HOST_CONTAINER}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: redis-cache
    networks:
      - alma-network

networks:
  alma-network:
    external: true
