# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BACK-ALMA CI - Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  pre-merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test

    - name: Code review
      run: npx eslint .
      
    - name: Check version
      run: |
          VERSION=$(node -p "require('./package.json').version")
          CURRENT_TAG=$(git tag --points-at HEAD)
          if [ "$VERSION" != "$CURRENT_TAG" ]; then
            echo "::error::Please update the version in package.json before merging."
            exit 1
          fi
